socialsite/social_network/urls.py
from django.conf.urls import url

from . import views
app_name='social_network'
urlpatterns = [
    url(r'^home/', views.home, name='home'),
    url(r'^user_login/', views.user_login, name='user_login'),
    url(r'^user_signup/', views.user_signup, name='user_signup'),
    url(r'^signup_auth/', views.signup_auth, name='signup_auth'),
    url(r'^user_wall/', views.user_wall, name='user_wall'),
    url(r'^$', views.user_login, name='user_login'),
    url(r'^user_auth/', views.user_auth, name='user_auth'),
    url(r'^user_logout/', views.user_logout, name='user_logout'),
    url(r'^add_status/', views.add_status, name='add_status'), 
    url(r'^(?P<post_id>[0-9]+)/$', views.add_comment, name='add_comment'),
    url(r'^user/(?P<user_id>[0-9]+)/$', views.show_user, name='show_user'),


]

socialsite/socialsite/urls.py
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings



urlpatterns = [
    url(r'^', include('social_network.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socialsite/social_network/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
import datetime
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.models import User

# Create your models here.



class Post(models.Model):
    post_text = models.CharField(max_length=500)
    pub_date = models.DateTimeField('date published')
    username = models.CharField(max_length=200,default="anonymous")
    image=models.FileField(upload_to='images/%Y/%m/%d',default='no image available for this post')
    def __str__(self): 
        return self.post_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
        


'''
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
'''        


class Comment(models.Model):
	post=models.ForeignKey(Post,on_delete=models.CASCADE)
	username=models.CharField(max_length=200,default='none')
	comment_text=models.CharField(max_length=200)
    	
	def __str__(self):
		return self.comment_text
	

socialsite/social_network/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from .models import Post
from django.template import loader
from django.http import Http404
from django .core.urlresolvers import reverse
from django.views import generic
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.models import User
from django.utils import timezone




def home(request):
    posts=Post.objects.order_by('-pub_date')
    users=User.objects.all
    context={'posts':posts,'user':request.user,'users':users}
    return render(request,'social_network/home.html',context)

def user_login(request):
    posts=Post.objects.order_by('-pub_date')
    return render(request,'social_network/login.html')

def user_signup(request):
    
    return render(request,'social_network/signup.html')    

def user_auth(request):
	uname=request.POST['username']
	passd=request.POST['password']

	user=authenticate(username=uname,password=passd)
	if user is not None:
		if user.is_active:
			login(request,user)
			return HttpResponseRedirect(reverse('social_network:home'))    

def signup_auth(request):
	uname=request.POST['username']
	passd=request.POST['password']
	email=request.POST['email']

	user=User.objects.create_user(uname,email,passd)
	user.first_name=request.POST['firstname']
	user.last_name=request.POST['lastname']

	user.save()

	return HttpResponseRedirect(reverse('social_network:user_login'))

			
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('social_network:user_login'))	

def add_status(request):
	status=request.POST['status']
	post=Post(post_text=status,pub_date=timezone.now(),username=request.user.username,image=request.FILES['image'])
	post.save()
	return HttpResponseRedirect(reverse('social_network:home'))

def add_comment(request,post_id):
	post=get_object_or_404(Post,pk=post_id)
	comment=request.POST['comment']
	c=post.comment_set.create(comment_text=comment,username=request.user.username)
	c.save()
	return HttpResponseRedirect(reverse('social_network:home'))

def user_wall(request):
	posts=Post.objects.filter(username=request.user.username).order_by('-pub_date')
	users=User.objects.all
	context={'posts':posts,'user':request.user,'users':users}
	return render(request,'social_network/user_info.html',context)

def show_user(request,user_id):
	user=get_object_or_404(User,pk=user_id)
	posts=Post.objects.filter(username=user.username).order_by('-pub_date')
	users=User.objects.all
	context={'posts':posts,'user':request.user,'users':users}
	return render(request,'social_network/view_user.html',context)	

socialsite/social_network/templates/social_network/home.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
<head>
  <title>Mindchirp:Home</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <!--<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" /> 
  -->
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      
      border-radius: 0;
    }
    
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }
    .profpic {

      margin-right : 25px;
      padding : 10px;
    }
    #roller-info{

      font-size: 15px
      margin-bottom:30px;
      padding: 0px
      

    }
    #tip-info{

      font-size: 15px
      margin-bottom:30px;
      padding : 20px 
      

    }
    #super-info{

      font-size: 15px
      margin-bottom:30px;
      padding: 0px


    }

    
    

    #hello {

      font-family: arial black;
      font-style:italic;

    }
    #about{

      font-size:24px;
    }
    #col-header{

      font-family:verdana;
      font-size:18px;
      font-style:bold;
      text-align: center;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;} 
    }

    #col-body{

      font-family: verdana;
      font-size: 18px;
      text-align: center;
    }
    #other{

      font-family: verdana;
      font-size: 18px;
      margin-bottom: 10px;
      margin-left:20px;
      padding-right:50px;
    }
    #otherlast{

      font-family: verdana;
      font-size: 18px;
      margin-bottom: 100px;
      margin-left: 20px;
      padding-right: 50px
    }
    .right{

      padding-right: 20px;
    }

    #label
    {
    	text-align: left;
    	font-size : 18px;
    	font-family : verdana;
    }
    #textarea
    {
    	padding-left : 20px;
    	padding-right : 20px;
    }
    #panel-body
    {
    	/*padding-left : 20px;
    	padding-right : 20px;*/	
    }
    #user_info
    {
    	font-size:20px;
    	font-family:verdana;
    	
    }
    #body
    {
    	margin-bottom: 400px;
    }
    #q_authordetails
    {
    	 font-size: 15px;
    	 font-family: verdana;
    	 font-style: italic;
    }
    
    
   #scrollablebody {
    
    overflow-y: scroll; 
  }

    



    
  </style>

  
 


</head>
<body id="body">

	<nav class="navbar navbar-default">
  		<div class="container-fluid">
    		<div class="navbar-header">
      			<a class="navbar-brand" href="#">MindChirp</a>
    			</div>
    		<ul class="nav navbar-nav">
      			<li class="active"><a href="#">Home</a></li>
      			
    		</ul>
    		<ul class="nav navbar-nav navbar-right">
    			<li><a href="{% url 'social_network:user_wall' %}"><span class="glyphicon glyphicon-user"></span> {{ user.username }}</a></li>
      			<li><a href="{% url 'social_network:user_logout' %}"> Log out</a></li>
      
    		</ul>
  		</div>
	</nav>	
	<div class="container">
		<div id="user_info">
			Hello {{ user.username }}!!
		</div>

	<div class="row">
        <div class="col-sm-4">
            <div class="page-header" id='col-header'>
              Present users
            </div>
            <div id="col-body" id="scrollablebody">
            	
            		<div class='panel panel-default'>
            			
            			<div class='panel-body'> 

            				<div class='list-group'>
            					{% for user in users %}
            						<li class='list-group-item'>
            							<a href="{% url 'social_network:show_user' user.id %}" > {{ user.username }} </a>
            						</li>
            					{% endfor %}	
            				</div>
		              		
				  		</div>			
			  		</div>		
		  				
		  				
	  					
            
          	</div>
    	</div>	

    	<div class="col-sm-4">
            <!--<div class="page-header" id='col-header'>
              
            </div>-->
            
            	
            		<!---<div class='panel panel-default'>
            			
            			<div class='panel-body'> -->

            				<form method="post" action="{% url 'social_network:add_status' %}" role='form' class='form-horizontal' enctype="multipart/form-data">
            					<div class='form-group'>
								 	{% csrf_token %}
								 	<input type='file' name='image' accept='image/*' class="btn btn-primary btn-sm">
								 	<label for="status">Speak your mind</label>
								 	<textarea id="status"  rows="5" name='status' class='form-control'></textarea>
								 	<input type="submit" value="post" class='btn btn-primary btn-sm btn-block'>
								</div> 	
							</form>
							</br>

							{% if posts %}
								{% for post in posts %}
									<div class="row">
            							<div class='col-sm-4'>
            								<div class="col-body">
            									<div id="q_authordetails">
            										Auther:{{ post.username }}
            										</br>
            										{{ post.pub_date }}
            									</div>	
            								</div>
            							</div>
            							<div class='col-sm-4'>
            								<div class="col-body">
            									{{ post.post_text }}
            									<img src='{{ post.image.url }}' alt=''>
            								</div>
            							</div>
            						</div>
									{% if post.comment_set.all %}
										{% for comment in post.comment_set.all %}
											<div class="row">
            									<div class='col-sm-4'>
            										<div class="col-body">
            											<div id="q_authordetails">
            												Auther:{{ comment.username }}
            											
            											</div>	
            										</div>
            									</div>
            									<div class='col-sm-4'>
            										<div class="col-body">
            											{{ comment.comment_text }}
            										</div>
            									</div>
            								</div>
											
										{% endfor %}	

									{% else %}
										<p> No comments available for this posts </p>	
									{% endif %}
									<form method="POST" action="{% url 'social_network:add_comment' post.id %}" role='form' class='form-horizontal'>
										{% csrf_token %}
										<label for="comment">Add comment</label></br>
										<input type='text' id="comment" name="comment" class='form-control'>
										<input type='submit' value='comment' class='btn btn-primary btn-sm btn-block'>
									</form>		
								{% endfor %}		
		
							{% else %}
								<h4> No post available </h4>
							{% endif %}		
		              		
				  		<!--</div>			
			  		</div>	-->	
		  				
		  				
	  					
            
          	
    	</div>	

    </div>	


	 
	 














	</div>

</body>
</html>

socialsite/social_network/templates/social_network/login.html
{% load staticfiles %}

<!DOCTYPE html>
<head>
<h4> Provide credentials </h4>
</head>

<body>
<p>
<a href="{% url 'social_network:user_signup' %}">sign up</a>
</p>
<form method="POST" action="{% url 'social_network:user_auth' %}" >
{% csrf_token %}
<label for="username">User name</label>
<input type="text" name="username" id="username" >
<label for="password">Password</label>
<input type="password" name="password" id="password" >
<input type="submit" value="login">
</form>
</body>
</html>

socialsite/social_network/templates/social_network/signup.html
{% load staticfiles %}

<!DOCTYPE html>
<head>
<h4> Provide credentials </h4>
</head>

<body>
<p>
<a href="{% url 'social_network:user_login' %}">login</a>
</p>
<form method="POST" action="{% url 'social_network:signup_auth' %}" >
{% csrf_token %}
<label for="username">Username</label>
<input type="text" name="username" id="username" ></br>
<label for="password">Password</label>
<input type="password" name="password" id="password" ></br>
<label for="firstname">First name</label>
<input type="text" name="firstname" id="firstname" ></br>
<label for="lastname">Last name </label>
<input type="text" name="lastname" id="lastname" > </br>
<label for="email">Email</label>
<input type="text" name="email" id="email"></br>
<input type="submit" value="signup">
</form>
</body>
</html>

socialsite/social_network/templates/social_network/user_info.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
<head>
  <title>Mindchirp:{{ user.username }}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <!--<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" /> 
  -->
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      
      border-radius: 0;
    }
    
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }
    .profpic {

      margin-right : 25px;
      padding : 10px;
    }
    #roller-info{

      font-size: 15px
      margin-bottom:30px;
      padding: 0px
      

    }
    #tip-info{

      font-size: 15px
      margin-bottom:30px;
      padding : 20px 
      

    }
    #super-info{

      font-size: 15px
      margin-bottom:30px;
      padding: 0px


    }

    
    

    #hello {

      font-family: arial black;
      font-style:italic;

    }
    #about{

      font-size:24px;
    }
    #col-header{

      font-family:verdana;
      font-size:18px;
      font-style:bold;
      text-align: center;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;} 
    }

    #col-body{

      font-family: verdana;
      font-size: 18px;
      text-align: center;
    }
    #other{

      font-family: verdana;
      font-size: 18px;
      margin-bottom: 10px;
      margin-left:20px;
      padding-right:50px;
    }
    #otherlast{

      font-family: verdana;
      font-size: 18px;
      margin-bottom: 100px;
      margin-left: 20px;
      padding-right: 50px
    }
    .right{

      padding-right: 20px;
    }

    #label
    {
    	text-align: left;
    	font-size : 18px;
    	font-family : verdana;
    }
    #textarea
    {
    	padding-left : 20px;
    	padding-right : 20px;
    }
    #panel-body
    {
    	/*padding-left : 20px;
    	padding-right : 20px;*/	
    }
    #user_info
    {
    	font-size:20px;
    	font-family:verdana;
    	
    }
    #body
    {
    	margin-bottom: 400px;
    }
    #q_authordetails
    {
    	 font-size: 15px;
    	 font-family: verdana;
    	 font-style: italic;
    }
    
    
   #scrollablebody {
    
    overflow-y: scroll; 
  }

    



    
  </style>

  
 


</head>
<body id="body">

	<nav class="navbar navbar-default">
  		<div class="container-fluid">
    		<div class="navbar-header">
      			<a class="navbar-brand" href="#">MindChirp</a>
    			</div>
    		<ul class="nav navbar-nav">
      			<li class="active"><a href="{% url 'social_network:home' %}">Home</a></li>
      			
    		</ul>
    		<ul class="nav navbar-nav navbar-right">
    			<li><a href="#"><span class="glyphicon glyphicon-user"></span> {{ user.username }}</a></li>
      			<li><a href="{% url 'social_network:user_logout' %}"> Log out</a></li>
      
    		</ul>
  		</div>
	</nav>	
	<div class="container">
		<div id="user_info">
			Hello {{ user.username }}!!
		</div>

	<div class="row">
        <div class="col-sm-4">
            <div class="page-header" id='col-header'>
              Present users
            </div>
            <div id="col-body" id="scrollablebody">
            	
            		<div class='panel panel-default'>
            			
            			<div class='panel-body'> 
            			
            				<div class='list-group'>
            					{% for user in users %}
            						<li class='list-group-item'>
            							<a href="{% url 'social_network:show_user' user.id %}" > {{ user.username }} </a>
            						</li>
            					{% endfor %}	
            				</div>	
		              		
				  		</div>			
			  		</div>		
		  				
		  				
	  					
            
          	</div>
    	</div>	

    	<div class="col-sm-4">
            
            <div id="col-body" id="scrollablebody">
            	
            		<!---<div class='panel panel-default'>
            			
            			<div class='panel-body'> -->

            				<form method="POST" action="{% url 'social_network:add_status' %}" role='form' class='form-horizontal'>
            					<div class='form-group'>
								 	{% csrf_token %}
								 	<input type='file' name='image' accept='image/*' class="btn btn-primary btn-sm">
								 	<label for="status">Speak your mind</label>
								 	<textarea id="status"  rows="5" name='status' class='form-control'></textarea>
								 	<input type="submit" value="post" class='btn btn-primary btn-sm btn-block'>
								</div> 	
							</form>
							</br>

							{% if posts %}
								{% for post in posts %}
									<div class="row">
            							<div class='col-sm-4'>
            								<div class="col-body">
            									<div id="q_authordetails">
            										
            										{{ post.pub_date }}
            									</div>	
            								</div>
            							</div>
            							<div class='col-sm-4'>
            								<div class="col-body">
            									{{ post.post_text }}
            									<img src="{{ post.image.url }}">
            								</div>
            							</div>
            						</div>
            						</br>
									{% if post.comment_set.all %}
										{% for comment in post.comment_set.all %}
											<div class="row">
            									<div class='col-sm-4'>
            										<div class="col-body">
            											<div id="q_authordetails">
            												Auther:{{ comment.username }}
            											
            											</div>	
            										</div>
            									</div>
            									<div class='col-sm-4'>
            										<div class="col-body">
            											{{ comment.comment_text }}
            										</div>
            									</div>
            								</div>
											
										{% endfor %}	

									{% else %}
										<p> No comments available for this posts </p>	
									{% endif %}
									<form method="POST" action="{% url 'social_network:add_comment' post.id %}" role='form' class='form-horizontal'>
										{% csrf_token %}
										<label for="comment">Add comment</label></br>
										<input type='text' id="comment" name="comment" class='form-control'>
										<input type='submit' value='comment' class='btn btn-primary btn-sm btn-block'>
									</form>		
								{% endfor %}		
		
							{% else %}
								<h4> No post available </h4>
							{% endif %}		
		              		
				  		<!--</div>			
			  		</div>	-->	
		  				
		  				
	  					
            
          	</div>
    	</div>	

    </div>	


	 
	 














	</div>

</body>
</html>

socialsite/social_network/templates/social_network/view_user.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
<head>
  <title>Mindchirp</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <!--<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" /> 
  -->
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      
      border-radius: 0;
    }
    
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }
    .profpic {

      margin-right : 25px;
      padding : 10px;
    }
    #roller-info{

      font-size: 15px
      margin-bottom:30px;
      padding: 0px
      

    }
    #tip-info{

      font-size: 15px
      margin-bottom:30px;
      padding : 20px 
      

    }
    #super-info{

      font-size: 15px
      margin-bottom:30px;
      padding: 0px


    }

    
    

    #hello {

      font-family: arial black;
      font-style:italic;

    }
    #about{

      font-size:24px;
    }
    #col-header{

      font-family:verdana;
      font-size:18px;
      font-style:bold;
      text-align: center;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;} 
    }

    #col-body{

      font-family: verdana;
      font-size: 18px;
      text-align: center;
    }
    #other{

      font-family: verdana;
      font-size: 18px;
      margin-bottom: 10px;
      margin-left:20px;
      padding-right:50px;
    }
    #otherlast{

      font-family: verdana;
      font-size: 18px;
      margin-bottom: 100px;
      margin-left: 20px;
      padding-right: 50px
    }
    .right{

      padding-right: 20px;
    }

    #label
    {
    	text-align: left;
    	font-size : 18px;
    	font-family : verdana;
    }
    #textarea
    {
    	padding-left : 20px;
    	padding-right : 20px;
    }
    #panel-body
    {
    	/*padding-left : 20px;
    	padding-right : 20px;*/	
    }
    #user_info
    {
    	font-size:20px;
    	font-family:verdana;
    	
    }
    #body
    {
    	margin-bottom: 400px;
    }
    #q_authordetails
    {
    	 font-size: 15px;
    	 font-family: verdana;
    	 font-style: italic;
    }
    
    
   #scrollablebody {
    
    overflow-y: scroll; 
  }

    



    
  </style>

  
 


</head>
<body id="body">

	<nav class="navbar navbar-default">
  		<div class="container-fluid">
    		<div class="navbar-header">
      			<a class="navbar-brand" href="#">MindChirp</a>
    			</div>
    		<ul class="nav navbar-nav">
      			<li class="active"><a href="{% url 'social_network:home' %}">Home</a></li>
      			
    		</ul>
    		<ul class="nav navbar-nav navbar-right">
    			<li><a href="#"><span class="glyphicon glyphicon-user"></span> {{ user.username }}</a></li>
      			<li><a href="{% url 'social_network:user_logout' %}"> Log out</a></li>
      
    		</ul>
  		</div>
	</nav>	
	<div class="container">
		<div id="user_info">
			Hello {{ user.username }}!!
		</div>

	<div class="row">
        <div class="col-sm-4">
            <div class="page-header" id='col-header'>
              Present users
            </div>
            <div id="col-body" id="scrollablebody">
            	
            		<div class='panel panel-default'>
            			
            			<div class='panel-body'> 

                  
                    <div class='list-group'>
                      {% for user in users %}
                        <li class='list-group-item'>
                          <a href="{% url 'social_network:show_user' user.id %}" > {{ user.username }} </a>
                        </li>
                      {% endfor %}  
                    </div>
		              		
				  		  </div>			
			  		</div>		
		  				
		  				
	  					
            
          	</div>
    	</div>	

    	<div class="col-sm-4">
            
            <div id="col-body" id="scrollablebody">
            	
            		<!---<div class='panel panel-default'>
            			
            			<div class='panel-body'> -->

            				
							

							{% if posts %}
								{% for post in posts %}
									<div class="row">
            							<div class='col-sm-4'>
            								<div class="col-body">
            									<div id="q_authordetails">
            										
            										{{ post.pub_date }}
            									</div>	
            								</div>
            							</div>
            							<div class='col-sm-4'>
            								<div class="col-body">
            									{{ post.post_text }}
                              <img src="{{ post.image.url }}">
            								</div>
            							</div>
            						</div>
            						</br>
									{% if post.comment_set.all %}
										{% for comment in post.comment_set.all %}
											<div class="row">
            									<div class='col-sm-4'>
            										<div class="col-body">
            											<div id="q_authordetails">
            												Auther:{{ comment.username }}
            											
            											</div>	
            										</div>
            									</div>
            									<div class='col-sm-4'>
            										<div class="col-body">
            											{{ comment.comment_text }}
            										</div>
            									</div>
            								</div>
											
										{% endfor %}	

									{% else %}
										<p> No comments available for this posts </p>	
									{% endif %}
									<form method="POST" action="{% url 'social_network:add_comment' post.id %}" role='form' class='form-horizontal'>
										{% csrf_token %}
										<label for="comment">Add comment</label></br>
										<input type='text' id="comment" name="comment" class='form-control'>
										<input type='submit' value='comment' class='btn btn-primary btn-sm btn-block'>
									</form>		
								{% endfor %}		
		
							{% else %}
								<h4> No post available </h4>
							{% endif %}		
		              		
				  		<!--</div>			
			  		</div>	-->	
		  				
		  				
	  					
            
          	</div>
    	</div>	

    </div>	


	 
	 














	</div>

</body>
</html>